#ifndef DBMANAGER_GLOBAL_H
#define DBMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(DBMANAGER_LIB)
#  define DBMANAGER_DB_CONNECTION_EXPORT Q_DECL_EXPORT
#  define DBMANAGER_DB_CONNECTION_SQLITE_EXPORT Q_DECL_EXPORT
#  define DBMANAGER_DB_CONNECTION_SQLSERVER_EXPORT Q_DECL_EXPORT
#  define DBMANAGER_DB_CHECKTHREAD_EXPORT Q_DECL_EXPORT
#  define DBMANAGER_DB_DBDIALOG_EXPORT Q_DECL_EXPORT
#  define DBMANAGER_DB_EXCEPTIONS_EXPORT Q_DECL_EXPORT
# else
#  define DBMANAGER_DB_CONNECTION_EXPORT Q_DECL_IMPORT
#  define DBMANAGER_DB_CONNECTION_SQLITE_EXPORT Q_DECL_IMPORT
#  define DBMANAGER_DB_CONNECTION_SQLSERVER_EXPORT Q_DECL_IMPORT
#  define DBMANAGER_DB_CHECKTHREAD_EXPORT Q_DECL_IMPORT
#  define DBMANAGER_DB_DBDIALOG_EXPORT Q_DECL_IMPORT
#  define DBMANAGER_DB_EXCEPTIONS_EXPORT Q_DECL_IMPORT
# endif
#else
# define DBMANAGER_DB_CONNECTION_EXPORT
# define DBMANAGER_DB_CONNECTION_SQLITE_EXPORT
# define DBMANAGER_DB_CONNECTION_SQLSERVER_EXPORT
# define DBMANAGER_DB_CHECKTHREAD_EXPORT
# define DBMANAGER_DB_DBDIALOG_EXPORT
# define DBMANAGER_DB_EXCEPTIONS_EXPORT
#endif
#endif // DBMANAGER_GLOBAL_H
