#ifndef QWEBAPPSOCKETUPGRADE_GLOBAL_H
#define QWEBAPPSOCKETUPGRADE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(QWEBAPPSOCKETUPGRADE_LIB)
#  define QWEBAPPSOCKETUPGRADE_EXPORT Q_DECL_EXPORT
# else
#  define QWEBAPPSOCKETUPGRADE_EXPORT Q_DECL_IMPORT
# endif
#else
# define QWEBAPPSOCKETUPGRADE_EXPORT
#endif
#endif // QWEBAPPSOCKETUPGRADE_GLOBAL_H
